version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    working_dir: /app/frontend
    command: ["npm", "run", "dev"]
    volumes:
      - ./frontend:/app/frontend
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    working_dir: /app/server
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
    volumes:
      - ./server:/app/server