version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    working_dir: /app
    command: ["sh", "-c", "npm run dev -- --host 0.0.0.0"]
    volumes:
      - ./frontend:/app
    environment:
      - CHOKIDAR_USEPOLLING=true

  signaling:
    build:
      context: ./server
      dockerfile: Dockerfile
    command: ["node", "signaling.js"]
    ports:
      - "8080:8080"
    volumes:
      - ./server:/app

  receiver:
    build:
      context: ./server
      dockerfile: python.Dockerfile
    command: ["uvicorn", "live_receiver:app", "--host", "0.0.0.0", "--port", "8001"]
    ports:
      - "8001:8001"
    volumes:
      - ./server:/app
